### ISSUE TITLE
Failed when trying to translate more than 5k lines

### ISSUE THREAD

**Issue by Sachha** [daugsbi/simpleen-cli#1]
Hi, 

I'm trying to translate 6K line in 4 langage, but for some reason it fail (probably because of the size i guess) with this error:

`(node:640) UnhandledPromiseRejectionWarning: Error: 500 - Request failed Request failed with status code 500
    at Task.task (C:\Users\Sacha\AppData\Roaming\npm\node_modules\simpleen\lib\commands\translate.js:51:39)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:640) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:640) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

I don't know what is the limit but when i try to translate smaller part, it work :)

Thanks

**Comment by daugsbi** [comment]
Hi Sachha,
I've checked your account and you reached the limit to translate during our beta. Sorry for that, but we need to keep our translation costs at a reasonable level. Please keep in mind that the main purpose of our tool is localization, handling of i18n files. 
I will keep this open, because of improper  error handling. Thanks for bringing this up.

Best regards
