### ISSUE TITLE
Wrong translation when limit reached on CLI

### ISSUE THREAD

**Issue by danielberebel** [daugsbi/simpleen-cli#3]
I gets wrong translated files when attempts to do ` simpleen translate ` :

From
`{
"changeStatus": {
        "header": "Change Status"
    }
}`
to
`{
  "changeStatus": {
    "header": "Ƈħȧȧƞɠḗḗ Şŧȧȧŧŭŭş"
  }
}`

I hope, at least, don't saving files if it can't translate something

**Comment by daugsbi** [comment]
You're right. Working on a new version this week.

Would you expect an error message that the quota is reached?
What would you expect in cases where only a part of the JSON file can be translated because the quota is reached? 

We will have a new command `simpleen usage` to request your current quota. 
Another command like `simpleen upload` will let you upload allready/adapted files. These will not count to the quota.

What do you think about our plan?

**Comment by danielberebel** [comment]
At CLI integration, the error can be displayed as warning terminal print. For Api integration, maybe, as HTTP error code ?
Some Frameworks has key fallback on translations (if can't find key on translation file it shows main lang translation), so if some key would can't be translate, it can remove from  output json

**Comment by daugsbi** [comment]
You can now check your current usage with `simpleen usage`. Additionally if you've reached the limit during translate it shows an information that you've reached the limit.

Instead of using pseudo localization we omit the untranslated structure to support the fallback feature of i18n libraries. Thanks a lot for your inputs. 

If you already have some translations, just use `simpleen upload` to sync your existing or adapted translation results. Already translated segments are not counted/limited to the quota.
